INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/search_name_cdna/fdls"
CDNA: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Fundulus_heteroclitus-3.0.2.cdna.all.fa"

