INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/search_name_cdna/stkb"
CDNA: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Gasterosteus_aculeatus.BROADS1.cdna.all.fa"

