INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/search_name_cdna/zf"
CDNA: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Danio_rerio.GRCz11.cdna.all.fa"

