INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/search_name_cdna/mdk"
CDNA: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Oryzias_latipes.ASM223467v1.cdna.all.fa"

