INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/search_name_cdna/cod"
CDNA: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Gadus_morhua.gadMor1.cdna.all.fa"

