INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/rbh/cod_gadMor1"

PEP_SEQ: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/Gadus_morhua.gadMor1.pep.all.fa"

E_HMMSEARCH: 10
EVALUE_BLAST: 10
NCORE: 30
