INPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input"
OUTPUTPATH: "/export/jonassenfs/xiaokangz/project/data/codDefensome/output/rbh/gadMor3"

PEP_SEQ: "/export/jonassenfs/xiaokangz/project/data/codDefensome/input/GCF_902167405.1_gadMor3.0_protein.faa"

E_HMMSEARCH: 10
EVALUE_BLAST: 10
NCORE: 30
